
name: MacOS Native

on:
  workflow_dispatch

jobs:

  macos-native-build-run:
    runs-on: macos-13
    steps:

# Toolchain + git

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install build tools
        run: python -m pip install meson ninja cmake

      - uses: actions/checkout@v4
      - name: Initialize git submodules
        run: git submodule update --init --recursive

# Native meson + cmake

      - name: Setup build directory meson native
        run: meson setup build-meson-native
      - name: Build application meson native
        run: ninja -C build-meson-native
      - name: Start application meson
        run: ./build-meson-native/app

      - name: Setup build directory cmake native
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build-cmake-native
      - name: Build application cmake native
        run: cmake --build build-cmake-native -j
      - name: Start application cmake
        run: ./build-cmake-native/app

